### PR TITLE
Add hypre configure parameter for enabling cuda UVM

### PR DESCRIPTION
**Pull request by jrood-nrel**
This is the `package.py` I am currently using on Eagle for testing.

### CODE REVIEW

**Review by sayerhs — APPROVED** [review]

**Review by PaulMullowney — COMMENTED** [review]
So, I'm not sure if this is the right path forward. I tried IJ interface without UVM and it works provided good options are chosen ... and may be faster. Part of me thinks that we should check all the options against the type of build and then error out, with a sensible message, if an incompatible option is chosen.

**Comment by jrood-nrel** [comment]
That sounds fair. Would `convTaylorVortex` just require modification then?

In regards to this PR, I think this should go in, but I will make another commit to turn the `cuda-uvm` variant off by default. So then the switch will work in the future if we need it for something.

**Comment by PaulMullowney** [comment]
Sounds good. Let’s get this in now. I’ll think about how to resolve this robustly.

-Paul

From: Jon Rood ***@***.***>
Reply-To: Exawind/exawind-builder ***@***.***>
Date: Monday, April 26, 2021 at 4:08 PM
To: Exawind/exawind-builder ***@***.***>
Cc: "Mullowney, Paul" ***@***.***>, Review requested ***@***.***>
Subject: Re: [Exawind/exawind-builder] Add hypre configure parameter for enabling cuda UVM (#27)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

That sounds fair. Would convTaylorVortex just require modification then?

In regards to this PR, I think this should go in, but I will make another commit to turn the cuda-uvm variant off by default. So then the switch will work in the future if we need it for something.

**Comment by jrood-nrel** [comment]
Ok I'm going to merge this then.

**Pull request merged**
